### ISSUE TITLE
how Simulate F12 when open tab

### ISSUE THREAD

**Issue by zettle** [Kholid060/automa-docs#10]
when I open new tab， I want to open chrome-devtools

but I can't find "F12" in "Press Key"

![image](https://user-images.githubusercontent.com/9694459/177138514-87928bab-4c2f-470b-be6b-fa0861037cd7.png)

**Comment by Kholid060** [comment]
I don't think that would be possible, because the press key block is only simulating pressing the key on the website page, which can't trigger the browser shortcut.
