### ISSUE TITLE
'nth-chind' unable to locate on same style name 

### ISSUE THREAD

**Issue by ktmswzw** [Kholid060/automa-docs#12]
## Cannot get span content of the same style name from the dynamic DIV list. Including using 'nth-chind' unable to locate
<img width="1191" alt="WX20220717-193053@2x" src="https://user-images.githubusercontent.com/6389084/179396102-f29f8941-2081-4846-a73f-152573048174.png">

`{{loopData@contacts}} .user-name` get name is ok

![1658057852195](https://user-images.githubusercontent.com/6389084/179396321-6b70e0be-9c3c-4f30-9289-ef790908a5cd.jpg)

and try 

`{{loopData@contacts}} .card-content-des` 

### error, becuse get the div has same div class for asynchronous

![1658058164387](https://user-images.githubusercontent.com/6389084/179396534-6fa0e4d0-139d-47f2-98cf-ae41178d3e99.jpg)

[test.automa.json.zip](https://github.com/AutomaApp/documentation/files/9127509/test.automa.json.zip)

https://user-images.githubusercontent.com/6389084/179396659-e6cde3db-c39b-4a2b-85ca-3307c6861d19.mp4

**Comment by Kholid060** [comment]
Try adding the element exists block before the get text block
