### ISSUE TITLE
JS custom event page

### ISSUE THREAD

**Issue by Fabian9799** [Kholid060/automa-docs#13]
After checking the workflow settings i came across the "Workflow public Id" setting for usage in custom js events
After a bit of searching i found [this issue](https://github.com/AutomaApp/automa/issues/382) which describes the js event a bit better. 

I think it would be nice to have an explanation of that on the docs page and maybe a small (i) icon in the automa settings page next to the js event description

**Comment by Kholid060** [comment]
I'll add it in the next update
