### ISSUE TITLE
Parameter prompt - what are the variable names used to access the inputs?

### ISSUE THREAD

**Issue by jddcef** [Kholid060/automa-docs#21]
On this page: https://docs.automa.site/blocks/parameter-prompt.html
please mention what the parameter variable names are?
Is it under variables@ or params@ or something like that?

**Comment by jddcef** [comment]
This page https://docs.automa.site/workflow/parameters.html#add-a-parameter says ` {{ variables.keyword }}`, do you mean to put the @ there? {{ variables@keyword }}

**Comment by Kholid060** [comment]
Both `{{ variables.keyword }}` and `{{ variables@keyword }}` is supported in the v1.22.0
