### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by MartinDelille** [Kholid060/automa-docs#34]
Image are missing here: https://github.com/AutomaApp/documentation/blob/main/docs/workflow/testing-mode.md

**Comment by kaovilai** [comment]
cloudinary appears to be down.

**Comment by eMPee584** [comment]
Cloudinary is up but the account this was hosted for has gone inactive.
Here's a working copy on the web archive:
https://web.archive.org/web/20240110013458/https://docs.automa.site/workflow/testing-mode.html
