### ISSUE TITLE
Hi, can you provide me with the pictures from the document?

### ISSUE THREAD

**Issue by AprildreamMI** [Kholid060/automa-docs#36]
Hi! I noticed that the image links on your documentation site are broken. If you can provide the images, I can store them in the documentation repository (https://github.com/AutomaApp/documentation) and the images will be saved in the documentation server and will not be broken anymore. I will replace the broken image links in the documentation with the new image links

**Comment by ch197511161** [comment]
Please fix these broken image links

**Comment by eMPee584** [comment]
Here's a copy on the web archive with working images:
https://web.archive.org/web/20231203210340/https://docs.automa.site/
If you come accross a specific one that does not work, you can click on that (defunct) image, open it in a new tab and replace the date string in the URL with an asterisk, as in:

https://web.archive.org/web/20240110082159im_/https://res.cloudinary.com/chat-story/image/upload/v1666082112/automa/chrome_K7BmBkZ2gZ_o7k6fi.png => https://web.archive.org/web/*/https://res.cloudinary.com/chat-story/image/upload/v1666082112/automa/chrome_K7BmBkZ2gZ_o7k6fi.png

You can even get the original last-modified time from the `x-archive-orig-last-modified` header 🤓
